version: "3.1"

services:
  otusdb:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydb
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      # - data:/var/lib/mysql
      - "./myconf:/etc/mysql/conf.d"
    ports:
      - "3309:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# volumes:
#   data:
